"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Search,
  FileText,
  Copy,
  Download,
  Trash2,
  Clock,
  Check,
  X,
  AlertCircle,
  CheckCircle2,
  ChevronDown,
  ExternalLink,
  Bug,
  ScanSearch,
} from "lucide-react";

interface BugAnalysis {
  title: string;
  description: string;
  steps_to_reproduce: string[];
  expected_result: string;
  actual_result: string;
  severity: "Low" | "Medium" | "High" | "Critical";
}

interface HistoryItem {
  id: string;
  timestamp: number;
  image: string;
  analysis: BugAnalysis;
}

const severityColors: Record<string, string> = {
  Critical: "bg-red-500 text-white",
  High: "bg-orange-500 text-white",
  Medium: "bg-yellow-500 text-yellow-950",
  Low: "bg-green-500 text-white",
};

const severityBgColors: Record<string, string> = {
  Critical: "bg-red-500/10 border-red-500/20",
  High: "bg-orange-500/10 border-orange-500/20",
  Medium: "bg-yellow-500/10 border-yellow-500/20",
  Low: "bg-green-500/10 border-green-500/20",
};

export default function ReportsPage() {
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [search, setSearch] = useState("");
  const [filterSeverity, setFilterSeverity] = useState<string>("All");
  const [selectedReport, setSelectedReport] = useState<HistoryItem | null>(
    null
  );
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("qa-insight-history");
    if (saved) {
      try {
        setHistory(JSON.parse(saved));
      } catch {}
    }
  }, []);

  const deleteReport = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    const newHistory = history.filter((item) => item.id !== id);
    setHistory(newHistory);
    localStorage.setItem("qa-insight-history", JSON.stringify(newHistory));
    if (selectedReport?.id === id) {
      setSelectedReport(null);
    }
  };

  const clearAllReports = () => {
    setHistory([]);
    localStorage.removeItem("qa-insight-history");
    setSelectedReport(null);
  };

  const filteredHistory = history.filter((item) => {
    const matchesSearch =
      item.analysis.title.toLowerCase().includes(search.toLowerCase()) ||
      item.analysis.description.toLowerCase().includes(search.toLowerCase());
    const matchesSeverity =
      filterSeverity === "All" || item.analysis.severity === filterSeverity;
    return matchesSearch && matchesSeverity;
  });

  const formatReport = (item: HistoryItem) => {
    const a = item.analysis;
    return `BUG REPORT: ${a.title || "Untitled Bug"}
SEVERITY: ${a.severity || "Medium"}

DESCRIPTION:
${a.description || "No description provided."}

STEPS TO REPRODUCE:
${(a.steps_to_reproduce || []).map((step, i) => `${i + 1}. ${step}`).join("\n")}

EXPECTED RESULT:
${a.expected_result || "Not specified"}

ACTUAL RESULT:
${a.actual_result || "Not specified"}

---
Generated by QA Insight • ${new Date(item.timestamp).toLocaleString()}`;
  };

  const handleCopy = async (item: HistoryItem) => {
    await navigator.clipboard.writeText(formatReport(item));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (item: HistoryItem) => {
    const text = formatReport(item);
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bug-report-${item.analysis.title.toLowerCase().replace(/\s+/g, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen p-6 md:p-10 space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <h1 className="text-3xl font-bold tracking-tight">Bug Reports</h1>
          <p className="text-sm text-muted-foreground">
            View and manage all your saved bug reports.
          </p>
        </div>
        {history.length > 0 && (
          <Button
            variant="destructive"
            size="sm"
            onClick={clearAllReports}
            className="gap-2">
            <Trash2 className="h-4 w-4" />
            Clear All
          </Button>
        )}
      </div>

      {/* Filters */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search reports by title or description..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>
        <div className="relative inline-block text-left">
          <select
            value={filterSeverity}
            onChange={(e) => setFilterSeverity(e.target.value)}
            className="appearance-none rounded-lg border border-border bg-background px-3 py-2 pr-8 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-ring cursor-pointer">
            <option value="All">All Severity</option>
            <option value="Critical">Critical</option>
            <option value="High">High</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>
          <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 h-4 w-4 pointer-events-none text-muted-foreground" />
        </div>
        <div className="flex items-center gap-2 text-sm text-muted-foreground shrink-0">
          <Bug className="h-4 w-4" />
          <span>{filteredHistory.length} report{filteredHistory.length !== 1 ? "s" : ""}</span>
        </div>
      </div>

      {/* Reports Grid */}
      {filteredHistory.length > 0 ? (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {filteredHistory.map((item) => (
            <Card
              key={item.id}
              onClick={() => setSelectedReport(item)}
              className={`border-border/60 shadow-sm hover:shadow-lg transition-all cursor-pointer group overflow-hidden ${
                selectedReport?.id === item.id
                  ? "ring-2 ring-primary shadow-lg"
                  : ""
              }`}>
              <CardContent className="p-0">
                {/* Image */}
                <div className="relative h-36 overflow-hidden">
                  <Image
                    src={item.image}
                    alt={item.analysis.title}
                    fill
                    className="object-cover opacity-80 group-hover:opacity-100 transition-all"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" />
                  <span
                    className={`absolute top-3 left-3 rounded-full px-2.5 py-1 text-[10px] font-bold ${severityColors[item.analysis.severity]}`}>
                    {item.analysis.severity}
                  </span>
                  <Button
                    variant="destructive"
                    size="icon"
                    className="absolute right-2 top-2 h-7 w-7 rounded-full opacity-0 group-hover:opacity-100 transition-opacity shadow-md"
                    onClick={(e) => deleteReport(item.id, e)}>
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </div>

                {/* Content */}
                <div className="p-4 space-y-3">
                  <h3 className="font-semibold text-sm leading-snug line-clamp-2">
                    {item.analysis.title || "Untitled Bug"}
                  </h3>
                  <p className="text-xs text-muted-foreground line-clamp-2 leading-relaxed">
                    {item.analysis.description || "No description"}
                  </p>
                  <div className="flex items-center justify-between pt-1 border-t border-border/50">
                    <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
                      <Clock className="h-3 w-3" />
                      {new Date(item.timestamp).toLocaleDateString("en-US", {
                        month: "short",
                        day: "numeric",
                        year: "numeric",
                      })}
                    </div>
                    <div className="flex items-center gap-1">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleCopy(item);
                        }}>
                        {copied ? (
                          <Check className="h-3.5 w-3.5 text-green-500" />
                        ) : (
                          <Copy className="h-3.5 w-3.5" />
                        )}
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDownload(item);
                        }}>
                        <Download className="h-3.5 w-3.5" />
                      </Button>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <Card className="border-border/60 shadow-sm">
          <CardContent className="p-16 flex flex-col items-center justify-center text-center space-y-4">
            <div className="flex items-center justify-center w-16 h-16 rounded-full bg-muted">
              {search || filterSeverity !== "All" ? (
                <Search className="h-8 w-8 text-muted-foreground" />
              ) : (
                <FileText className="h-8 w-8 text-muted-foreground" />
              )}
            </div>
            <div className="space-y-1">
              <h3 className="font-semibold text-lg">
                {search || filterSeverity !== "All"
                  ? "No reports found"
                  : "No bug reports yet"}
              </h3>
              <p className="text-sm text-muted-foreground max-w-xs">
                {search || filterSeverity !== "All"
                  ? "Try adjusting your search or filter criteria."
                  : "Analyze a bug screenshot to generate your first report."}
              </p>
            </div>
            {!search && filterSeverity === "All" && (
              <Button asChild className="gap-2">
                <Link href="/analyze">
                  <ScanSearch className="h-4 w-4" />
                  Analyze a Bug
                </Link>
              </Button>
            )}
            {(search || filterSeverity !== "All") && (
              <Button
                variant="outline"
                onClick={() => {
                  setSearch("");
                  setFilterSeverity("All");
                }}
                className="gap-2">
                Clear Filters
              </Button>
            )}
          </CardContent>
        </Card>
      )}

      {/* Report Detail Dialog */}
      <Dialog
        open={!!selectedReport}
        onOpenChange={() => setSelectedReport(null)}>
        <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <div className="flex items-center justify-between pr-8">
              <DialogTitle className="text-lg font-bold">
                Bug Report Details
              </DialogTitle>
              <span
                className={`rounded-full px-3 py-1 text-xs font-bold ${severityColors[selectedReport?.analysis.severity || "Medium"]}`}>
                {selectedReport?.analysis.severity}
              </span>
            </div>
          </DialogHeader>

          {selectedReport && (
            <div className="space-y-6 pt-2">
              {/* Source Image */}
              <div className="relative aspect-video w-full overflow-hidden rounded-xl border border-border bg-muted">
                <Image
                  src={selectedReport.image}
                  alt={selectedReport.analysis.title}
                  fill
                  className="object-contain"
                />
              </div>

              {/* Report Fields */}
              <div className="space-y-5">
                <div>
                  <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">
                    Bug Title
                  </p>
                  <p className="text-base font-semibold">
                    {selectedReport.analysis.title || "Untitled Bug"}
                  </p>
                </div>

                <div>
                  <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">
                    Description
                  </p>
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    {selectedReport.analysis.description || "No description provided."}
                  </p>
                </div>

                <div>
                  <p className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">
                    Steps to Reproduce
                  </p>
                  <ol className="space-y-2">
                    {(selectedReport.analysis.steps_to_reproduce || []).map(
                      (step, i) => (
                        <li key={i} className="flex items-start gap-3 text-sm">
                          <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-muted text-[10px] font-bold mt-0.5">
                            {i + 1}
                          </span>
                          <span>{step}</span>
                        </li>
                      )
                    )}
                  </ol>
                </div>

                <div className="grid gap-4 sm:grid-cols-2">
                  <div className={`rounded-xl border p-4 space-y-2 ${severityBgColors[selectedReport.analysis.severity]}`}>
                    <div className="flex items-center gap-2">
                      <CheckCircle2 className="h-4 w-4 text-green-600 dark:text-green-400" />
                      <p className="text-xs font-bold uppercase tracking-wider">
                        Expected Result
                      </p>
                    </div>
                    <p className="text-sm leading-relaxed">
                      {selectedReport.analysis.expected_result || "Not specified"}
                    </p>
                  </div>
                  <div className={`rounded-xl border p-4 space-y-2 ${severityBgColors[selectedReport.analysis.severity]}`}>
                    <div className="flex items-center gap-2">
                      <AlertCircle className="h-4 w-4 text-red-600 dark:text-red-400" />
                      <p className="text-xs font-bold uppercase tracking-wider">
                        Actual Result
                      </p>
                    </div>
                    <p className="text-sm leading-relaxed">
                      {selectedReport.analysis.actual_result || "Not specified"}
                    </p>
                  </div>
                </div>

                <div className="flex items-center justify-between rounded-lg border border-border bg-muted/30 p-3">
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <Clock className="h-3.5 w-3.5" />
                    {new Date(selectedReport.timestamp).toLocaleString()}
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleCopy(selectedReport)}
                      className="gap-2">
                      {copied ? (
                        <Check className="h-3.5 w-3.5" />
                      ) : (
                        <Copy className="h-3.5 w-3.5" />
                      )}
                      {copied ? "Copied" : "Copy"}
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDownload(selectedReport)}
                      className="gap-2">
                      <Download className="h-3.5 w-3.5" />
                      Download
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
