"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Upload,
  X,
  Loader2,
  AlertCircle,
  CheckCircle2,
  Info,
  Save,
  ChevronDown,
  Copy,
  Download,
  Check,
  Trash2,
  ArrowLeft,
} from "lucide-react";
import Link from "next/link";

interface BugAnalysis {
  title: string;
  description: string;
  steps_to_reproduce: string[];
  expected_result: string;
  actual_result: string;
  severity: "Low" | "Medium" | "High" | "Critical";
}

interface HistoryItem {
  id: string;
  timestamp: number;
  image: string;
  analysis: BugAnalysis;
}

export default function AnalyzePage() {
  const [image, setImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<BugAnalysis | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [isFinalized, setIsFinalized] = useState(false);
  const [copied, setCopied] = useState(false);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const savedHistory = localStorage.getItem("qa-insight-history");
    if (savedHistory) {
      try {
        setHistory(JSON.parse(savedHistory));
      } catch (e) {
        console.error("Failed to parse history", e);
      }
    }
  }, []);

  const saveHistory = (newHistory: HistoryItem[]) => {
    setHistory(newHistory);
    localStorage.setItem("qa-insight-history", JSON.stringify(newHistory));
  };

  const processFile = (file: File) => {
    if (!file.type.startsWith("image/")) {
      setError("Please upload an image file.");
      return;
    }

    const reader = new FileReader();
    reader.onloadend = () => {
      setImage(reader.result as string);
      setAnalysis(null);
      setError(null);
      setIsFinalized(false);
    };
    reader.readAsDataURL(file);
  };

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) processFile(file);
  };

  const onDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const onDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const onDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) processFile(file);
  }, []);

  const handleAnalyze = async () => {
    if (!image) return;

    setLoading(true);
    setError(null);
    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ image }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error("Failed to analyze bug");
      }

      const data = await response.json();
      setAnalysis(data);
    } catch (err: any) {
      setError(err.message || "An error occurred");
    } finally {
      setLoading(false);
    }
  };

  const handleFieldChange = (
    field: keyof BugAnalysis,
    value: string | string[],
  ) => {
    if (!analysis) return;
    setAnalysis({ ...analysis, [field]: value });
  };

  const handleStepChange = (index: number, value: string) => {
    if (!analysis || !analysis.steps_to_reproduce) return;
    const newSteps = [...analysis.steps_to_reproduce];
    newSteps[index] = value;
    handleFieldChange("steps_to_reproduce", newSteps);
  };

  const handleFinalize = () => {
    if (!analysis || !image) return;
    setIsFinalized(true);

    const newItem: HistoryItem = {
      id: crypto.randomUUID(),
      timestamp: Date.now(),
      image,
      analysis,
    };

    saveHistory([newItem, ...history].slice(0, 10));
  };

  const formatReport = (targetAnalysis?: BugAnalysis) => {
    const report = targetAnalysis || analysis;
    if (!report) return "";
    return `BUG REPORT: ${report.title || "Untitled Bug"}
SEVERITY: ${report.severity || "Medium"}

DESCRIPTION:
${report.description || "No description provided."}

STEPS TO REPRODUCE:
${(report.steps_to_reproduce || []).map((step, i) => `${i + 1}. ${step}`).join("\n")}

EXPECTED RESULT:
${report.expected_result || "Not specified"}

ACTUAL RESULT:
${report.actual_result || "Not specified"}

---
Generated by QA Insight`;
  };

  const handleCopy = async () => {
    const text = formatReport();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = formatReport();
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bug-report-${analysis?.title.toLowerCase().replace(/\s+/g, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const removeImage = () => {
    setImage(null);
    setAnalysis(null);
    setError(null);
    setIsFinalized(false);
  };

  const triggerFileInput = () => {
    fileInputRef.current?.click();
  };

  const ReportSkeleton = () => (
    <div className="space-y-6 animate-in fade-in duration-500">
      <Card className="border-border/60 shadow-sm overflow-hidden">
        <div className="h-1.5 w-full bg-muted animate-pulse" />
        <CardHeader className="p-6 pb-0 space-y-4">
          <div className="flex items-center justify-between">
            <div className="h-8 w-2/3 bg-muted rounded-md animate-pulse" />
            <div className="h-6 w-24 bg-muted rounded-full animate-pulse" />
          </div>
          <div className="h-20 w-full bg-muted/50 rounded-md animate-pulse" />
        </CardHeader>
        <CardContent className="p-6 space-y-8">
          <div className="space-y-4">
            <div className="h-4 w-32 bg-muted rounded animate-pulse" />
            <div className="space-y-3">
              {[1, 2, 3].map((i) => (
                <div key={i} className="flex gap-4 items-center">
                  <div className="h-6 w-6 rounded-full bg-muted animate-pulse" />
                  <div className="h-4 flex-1 bg-muted/50 rounded animate-pulse" />
                </div>
              ))}
            </div>
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="h-24 rounded-xl border border-border bg-muted/20 animate-pulse" />
            <div className="h-24 rounded-xl border border-border bg-muted/20 animate-pulse" />
          </div>
        </CardContent>
      </Card>
      <div className="flex items-center justify-center gap-2 text-muted-foreground text-xs font-medium">
        <Loader2 className="h-3 w-3 animate-spin" />
        AI is analyzing your screenshot...
      </div>
    </div>
  );

  return (
    <div className="min-h-screen p-6 md:p-10 space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between gap-4">
        <div className="space-y-1">
          <h1 className="text-3xl font-bold tracking-tight">Analyze Bug</h1>
          <p className="text-sm text-muted-foreground">
            Upload a screenshot and let AI generate a structured bug report.
          </p>
        </div>
        {(analysis || loading) && (
          <Button
            variant="outline"
            onClick={removeImage}
            disabled={loading}
            className="gap-2">
            <ArrowLeft className="h-4 w-4" />
            {loading ? "Analyzing..." : "New Analysis"}
          </Button>
        )}
      </div>

      {!analysis && !loading ? (
        <div className="grid gap-8 lg:grid-cols-3">
          {/* Upload Area */}
          <div className="lg:col-span-2">
            <Card
              className={`border-border/60 overflow-hidden transition-all duration-200 ${
                isDragging
                  ? "border-primary ring-2 ring-primary/20"
                  : "shadow-sm"
              }`}>
              <CardContent className="p-0">
                <div
                  onDragOver={onDragOver}
                  onDragLeave={onDragLeave}
                  onDrop={onDrop}
                  onClick={triggerFileInput}
                  className={`flex cursor-pointer flex-col items-center justify-center space-y-6 p-12 transition-colors ${
                    isDragging ? "bg-primary/5" : ""
                  }`}>
                  {!image ? (
                    <>
                      <div className="rounded-full bg-muted p-5">
                        <Upload className="h-9 w-9 text-muted-foreground" />
                      </div>
                      <div className="space-y-2 text-center">
                        <p className="text-lg font-semibold">
                          Click to upload or drag and drop
                        </p>
                        <p className="text-sm text-muted-foreground">
                          PNG, JPG or WebP (max. 10MB)
                        </p>
                      </div>
                      <Input
                        ref={fileInputRef}
                        type="file"
                        accept="image/*"
                        onChange={handleImageChange}
                        className="hidden"
                      />
                    </>
                  ) : (
                    <div className="relative w-full space-y-6">
                      <div className="relative aspect-video w-full overflow-hidden rounded-xl border border-border bg-muted">
                        <Image
                          src={image}
                          alt="uploaded image"
                          fill
                          className="object-contain"
                        />
                        <Button
                          variant="destructive"
                          size="icon"
                          className="absolute right-4 top-4 rounded-full shadow-lg"
                          onClick={(e) => {
                            e.stopPropagation();
                            removeImage();
                          }}>
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                      <Button
                        onClick={handleAnalyze}
                        disabled={loading}
                        className="h-12 w-full text-base shadow-sm font-semibold gap-2">
                        <ScanSearchIcon className="h-5 w-5" />
                        Generate Bug Report
                      </Button>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Sidebar Info */}
          <div className="space-y-4">
            <Card className="border-border/60 shadow-sm">
              <CardHeader className="p-5 pb-3">
                <CardTitle className="text-sm font-semibold">
                  How It Works
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4 p-5 pt-0">
                {[
                  {
                    step: "1",
                    title: "Upload Screenshot",
                    desc: "Drag and drop or click to upload a bug screenshot",
                  },
                  {
                    step: "2",
                    title: "AI Analysis",
                    desc: "Our AI analyzes the image to identify the bug",
                  },
                  {
                    step: "3",
                    title: "Review & Edit",
                    desc: "Review the generated report and make edits",
                  },
                  {
                    step: "4",
                    title: "Export",
                    desc: "Copy or download the final bug report",
                  },
                ].map((item) => (
                  <div key={item.step} className="flex items-start gap-3">
                    <div className="flex items-center justify-center w-6 h-6 rounded-full bg-primary/10 text-primary text-xs font-bold shrink-0 mt-0.5">
                      {item.step}
                    </div>
                    <div>
                      <p className="text-sm font-medium">{item.title}</p>
                      <p className="text-xs text-muted-foreground">
                        {item.desc}
                      </p>
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>

            <Card className="border-border/60 shadow-sm bg-primary/5 border-primary/20">
              <CardContent className="p-5 space-y-2">
                <div className="flex items-center gap-2 text-primary">
                  <Info className="h-4 w-4" />
                  <p className="text-sm font-semibold">Pro Tip</p>
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  For best results, upload screenshots that clearly show the
                  error message or unexpected behavior. Include the full window
                  or screen when possible.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      ) : (
        <div className="space-y-6 animate-in fade-in duration-500">
          {/* Actions Bar */}
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div
                className={`h-3 w-3 rounded-full ${
                  isFinalized
                    ? "bg-green-500"
                    : loading
                      ? "bg-yellow-500 animate-pulse"
                      : "bg-blue-500"
                }`}
              />
              <span className="text-sm font-medium text-muted-foreground">
                {loading
                  ? "AI is analyzing..."
                  : isFinalized
                    ? "Report saved"
                    : "Editing mode"}
              </span>
            </div>
            <div className="flex flex-wrap gap-2">
              {isFinalized ? (
                <>
                  <Button variant="outline" onClick={handleCopy} className="gap-2">
                    {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                    {copied ? "Copied" : "Copy Text"}
                  </Button>
                  <Button variant="outline" onClick={handleDownload} className="gap-2">
                    <Download className="h-4 w-4" />
                    Download .txt
                  </Button>
                </>
              ) : analysis ? (
                <Button
                  onClick={handleFinalize}
                  className="bg-green-600 hover:bg-green-700 gap-2 shadow-md">
                  <Save className="h-4 w-4" />
                  Finalize Report
                </Button>
              ) : null}
            </div>
          </div>

          <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
            {/* Report Card */}
            <div className="lg:col-span-2">
              {loading ? (
                <ReportSkeleton />
              ) : (
                analysis && (
                  <Card
                    className={`border-border/60 shadow-sm overflow-hidden transition-opacity ${
                      isFinalized ? "opacity-75 pointer-events-none" : ""
                    }`}>
                    <div
                      className={`h-1.5 w-full ${
                        analysis.severity === "Critical"
                          ? "bg-red-500"
                          : analysis.severity === "High"
                            ? "bg-orange-500"
                            : analysis.severity === "Medium"
                              ? "bg-yellow-500"
                              : "bg-green-500"
                      }`}
                    />
                    <CardHeader className="p-6 pb-0 space-y-4">
                      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                        <div className="flex-1">
                          <Input
                            value={analysis.title}
                            onChange={(e) =>
                              handleFieldChange("title", e.target.value)
                            }
                            className="text-2xl font-bold bg-transparent border-none p-0 focus-visible:ring-0 placeholder:text-muted-foreground/50 h-auto"
                            placeholder="Bug Title"
                          />
                        </div>
                        <div className="relative inline-block text-left">
                          <select
                            value={analysis.severity}
                            onChange={(e) =>
                              handleFieldChange(
                                "severity",
                                e.target.value as BugAnalysis["severity"],
                              )
                            }
                            className={`appearance-none rounded-full px-4 py-1.5 text-xs font-semibold ring-1 ring-inset focus:outline-none cursor-pointer pr-8 ${
                              analysis.severity === "Critical"
                                ? "bg-red-50 text-red-700 ring-red-600/20 dark:bg-red-950 dark:text-red-400"
                                : analysis.severity === "High"
                                  ? "bg-orange-50 text-orange-700 ring-orange-600/20 dark:bg-orange-950 dark:text-orange-400"
                                  : analysis.severity === "Medium"
                                    ? "bg-yellow-50 text-yellow-700 ring-yellow-600/20 dark:bg-yellow-950 dark:text-yellow-400"
                                    : "bg-green-50 text-green-700 ring-green-600/20 dark:bg-green-950 dark:text-green-400"
                            }`}>
                            <option value="Critical">Critical Priority</option>
                            <option value="High">High Priority</option>
                            <option value="Medium">Medium Priority</option>
                            <option value="Low">Low Priority</option>
                          </select>
                          <ChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 pointer-events-none opacity-50" />
                        </div>
                      </div>
                      <Textarea
                        value={analysis.description}
                        onChange={(e) =>
                          handleFieldChange("description", e.target.value)
                        }
                        className="min-h-[80px] bg-muted/30 border-border resize-none text-muted-foreground"
                        placeholder="Enter bug description..."
                      />
                    </CardHeader>

                    <CardContent className="p-6 space-y-8">
                      {/* Steps to Reproduce */}
                      <div className="space-y-4">
                        <div className="flex items-center gap-2">
                          <Info className="h-4 w-4 text-muted-foreground" />
                          <h3 className="text-sm font-bold uppercase tracking-wider text-muted-foreground">
                            Steps to Reproduce
                          </h3>
                        </div>
                        <div className="space-y-3">
                          {(analysis.steps_to_reproduce || []).map((step, i) => (
                            <div key={i} className="flex gap-4 items-start group">
                              <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-muted text-[10px] font-bold text-muted-foreground">
                                {i + 1}
                              </span>
                              <Input
                                value={step}
                                onChange={(e) =>
                                  handleStepChange(i, e.target.value)
                                }
                                className="bg-transparent border-none p-0 focus-visible:ring-0 h-auto text-foreground"
                              />
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Results Comparison */}
                      <div className="grid gap-4 sm:grid-cols-2">
                        <div className="rounded-xl border border-green-500/20 bg-green-500/5 p-5 dark:bg-green-500/5 space-y-2">
                          <div className="flex items-center gap-2 text-green-600 dark:text-green-400">
                            <CheckCircle2 className="h-4 w-4" />
                            <h4 className="text-xs font-bold uppercase tracking-wider">
                              Expected Result
                            </h4>
                          </div>
                          <Textarea
                            value={analysis.expected_result}
                            onChange={(e) =>
                              handleFieldChange(
                                "expected_result",
                                e.target.value,
                              )
                            }
                            className="bg-transparent border-none p-0 focus-visible:ring-0 min-h-[60px] resize-none text-sm leading-relaxed"
                          />
                        </div>

                        <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-5 dark:bg-red-500/5 space-y-2">
                          <div className="flex items-center gap-2 text-red-600 dark:text-red-400">
                            <AlertCircle className="h-4 w-4" />
                            <h4 className="text-xs font-bold uppercase tracking-wider">
                              Actual Result
                            </h4>
                          </div>
                          <Textarea
                            value={analysis.actual_result}
                            onChange={(e) =>
                              handleFieldChange(
                                "actual_result",
                                e.target.value,
                              )
                            }
                            className="bg-transparent border-none p-0 focus-visible:ring-0 min-h-[60px] resize-none text-sm leading-relaxed"
                          />
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                )
              )}
            </div>

            {/* Image Preview */}
            <div className="space-y-4">
              <Card className="border-border/60 shadow-sm overflow-hidden">
                <CardHeader className="p-4 border-b border-border">
                  <CardTitle className="text-sm font-medium text-muted-foreground">
                    Source Image
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-4 bg-muted/30">
                  <div className="relative aspect-square w-full overflow-hidden rounded-lg border border-border">
                    <Image
                      src={image!}
                      alt="Source"
                      fill
                      className="object-contain"
                    />
                  </div>
                </CardContent>
              </Card>

              {isFinalized && !loading && (
                <Card className="border-green-500/20 bg-green-500/5 shadow-sm">
                  <CardContent className="p-5 flex flex-col items-center justify-center text-center space-y-3">
                    <div className="flex items-center justify-center w-12 h-12 rounded-full bg-green-500/10">
                      <CheckCircle2 className="h-6 w-6 text-green-600 dark:text-green-400" />
                    </div>
                    <div>
                      <p className="font-semibold text-sm">Report Saved</p>
                      <p className="text-xs text-muted-foreground">
                        Saved to your local history.
                      </p>
                    </div>
                    <Button variant="outline" size="sm" asChild className="w-full gap-2">
                      <Link href="/reports">
                        <FileTextIcon className="h-4 w-4" />
                        View All Reports
                      </Link>
                    </Button>
                  </CardContent>
                </Card>
              )}
            </div>
          </div>
        </div>
      )}

      {error && (
        <div className="flex items-center gap-3 rounded-lg border border-red-500/20 bg-red-500/5 p-4 text-red-600 dark:text-red-400">
          <AlertCircle className="h-5 w-5 shrink-0" />
          <p className="text-sm font-medium">{error}</p>
        </div>
      )}
    </div>
  );
}

// Inline icon components
function ScanSearchIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
      <path d="M11 8v6" />
      <path d="M8 11h6" />
    </svg>
  );
}

function FileTextIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
      <line x1="16" x2="8" y1="13" y2="13" />
      <line x1="16" x2="8" y1="17" y2="17" />
      <line x1="10" x2="8" y1="9" y2="9" />
    </svg>
  );
}
